"""Tests for tools/emit_decision.py — Phase 2 Judgment Trail validator + appender.

Covers the full validation surface from the Phase 2 spec: identity auto-fill,
authority/calibration/classification rules, alternatives anti-gaming, grading
invariants, conditional rules, and CLI behavior.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
import unittest
from contextlib import contextmanager
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TOOLS_DIR = REPO_ROOT / "tools"
sys.path.insert(0, str(TOOLS_DIR))

import emit_decision  # noqa: E402

EmitDecisionError = emit_decision.DecisionValidationError


@contextmanager
def _env(**overrides):
    """Set env vars temporarily; restore on exit."""
    saved = {k: os.environ.get(k) for k in overrides}
    try:
        for k, v in overrides.items():
            if v is None:
                os.environ.pop(k, None)
            else:
                os.environ[k] = v
        yield
    finally:
        for k, original in saved.items():
            if original is None:
                os.environ.pop(k, None)
            else:
                os.environ[k] = original


def _valid_judgment_record(**overrides):
    """Returns a fresh valid judgment_driven record. Override via kwargs."""
    base = {
        "trace_id": "cc-PRO-TEST-aaaaaaaa-bbbbbbbb",
        "ticket_id": "PRO-TEST",
        "worker": "claude-code",
        "proposed_tag": "judgment_driven",
        "tool_profile": "standard_worker",
        "authority_mode": "limited_write",
        "trigger": "risk_classification",
        "decision_type": "risk",
        "decision": (
            "Classify the change as operator-merge because it creates a new tool " "and tests."
        ),
        "evidence_refs": ["AGENTS.md PR Merge Policy"],
        "canon_refs": [],
        "context_used": ["Task creates a new tool in tools/ and a new test file"],
        "alternatives_considered": [],
        "constraints": ["Phase 2 foundation only"],
        "assumptions": ["data/agent_decisions.jsonl follows existing JSONL placement"],
        "known_uncertainties": ["Final log path may change if guardrails require otherwise"],
        "confidence": "medium",
        "confidence_reason": "Merge policy is clear in canon, but specific files matter.",
        "would_change_mind_if": ("Existing canon explicitly allows this exact case as self-merge."),
        "expected_outcome": ("Decision record accepted and appended with pending_outcome state."),
        "outcome_evidence_refs": [],
        "verification_limitations": [],
    }
    base.update(overrides)
    return base


class _DecisionTestBase(unittest.TestCase):
    """Each test gets its own temp log path and isolated MIRU_TRACE_ID."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.log_path = Path(self._tmp.name) / "decisions.jsonl"
        # Default: clear MIRU_TRACE_ID so identity auto-fill behavior is
        # explicit per-test. Tests that need it set use _env().
        self._saved_trace = os.environ.pop("MIRU_TRACE_ID", None)
        self.addCleanup(self._restore_trace)

    def _restore_trace(self):
        if self._saved_trace is not None:
            os.environ["MIRU_TRACE_ID"] = self._saved_trace

    def _emit(self, record):
        return emit_decision.emit(record, log_path=self.log_path)

    def _read_lines(self):
        if not self.log_path.exists():
            return []
        return [
            json.loads(ln)
            for ln in self.log_path.read_text(encoding="utf-8").splitlines()
            if ln.strip()
        ]


# ---------------------------------------------------------------------------
# Happy path
# ---------------------------------------------------------------------------


class EmitDecisionHappyPathTests(_DecisionTestBase):
    def test_valid_judgment_driven_record_appends_one_line(self):
        record = _valid_judgment_record()
        result = self._emit(record)
        lines = self._read_lines()
        self.assertEqual(len(lines), 1)
        self.assertEqual(lines[0]["worker"], "claude-code")
        self.assertEqual(lines[0]["trigger"], "risk_classification")
        self.assertEqual(lines[0]["grading_state"], "pending_outcome")
        self.assertIn("decision_id", result)

    def test_decision_id_autogenerated_when_omitted(self):
        record = _valid_judgment_record()
        record.pop("decision_id", None)
        result = self._emit(record)
        self.assertIsInstance(result["decision_id"], str)
        self.assertEqual(len(result["decision_id"]), 32)  # uuid4().hex

    def test_created_at_autogenerated_when_omitted(self):
        record = _valid_judgment_record()
        record.pop("created_at", None)
        result = self._emit(record)
        self.assertRegex(result["created_at"], r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$")

    def test_two_emits_appends_two_distinct_lines(self):
        self._emit(_valid_judgment_record())
        self._emit(_valid_judgment_record())
        lines = self._read_lines()
        self.assertEqual(len(lines), 2)

    def test_grading_defaults_filled_in(self):
        record = _valid_judgment_record()
        for field in (
            "final_tag",
            "actual_outcome",
            "outcome_status",
            "graded_by",
            "graded_at",
            "grading_state",
            "classification_history",
        ):
            record.pop(field, None)
        result = self._emit(record)
        self.assertIsNone(result["final_tag"])
        self.assertIsNone(result["actual_outcome"])
        self.assertIsNone(result["outcome_status"])
        self.assertIsNone(result["graded_by"])
        self.assertIsNone(result["graded_at"])
        self.assertEqual(result["grading_state"], "pending_outcome")
        self.assertEqual(result["classification_history"], [])

    def test_idempotent_decision_id_collision_appends_two_rows(self):
        # Append-only is more important than uniqueness; collisions surface as
        # duplicate rows for downstream dedup, not silent merges.
        record1 = _valid_judgment_record(decision_id="explicit_collision_id")
        record2 = _valid_judgment_record(decision_id="explicit_collision_id")
        self._emit(record1)
        self._emit(record2)
        lines = self._read_lines()
        self.assertEqual(len(lines), 2)
        self.assertEqual(lines[0]["decision_id"], "explicit_collision_id")
        self.assertEqual(lines[1]["decision_id"], "explicit_collision_id")


# ---------------------------------------------------------------------------
# Identity
# ---------------------------------------------------------------------------


class EmitDecisionIdentityTests(_DecisionTestBase):
    def test_trace_id_autofill_from_env(self):
        record = _valid_judgment_record()
        record.pop("trace_id", None)
        record.pop("ticket_id", None)
        with _env(MIRU_TRACE_ID="cc-PRO-999-aaaaaaaa-bbbbbbbb"):
            result = self._emit(record)
        self.assertEqual(result["trace_id"], "cc-PRO-999-aaaaaaaa-bbbbbbbb")
        self.assertEqual(result["ticket_id"], "PRO-999")

    def test_missing_worker_rejected(self):
        record = _valid_judgment_record()
        record.pop("worker", None)
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("worker" in e for e in ctx.exception.errors))

    def test_missing_trace_id_with_no_env_rejected(self):
        record = _valid_judgment_record()
        record.pop("trace_id", None)
        record.pop("ticket_id", None)
        # _env(MIRU_TRACE_ID=None) clears it. setUp also clears.
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("trace_id" in e for e in ctx.exception.errors))


# ---------------------------------------------------------------------------
# Authority — explicit checks for the tool-profile / authority-mode separation.
# ---------------------------------------------------------------------------


class EmitDecisionAuthorityTests(_DecisionTestBase):
    def test_missing_tool_profile_rejected(self):
        record = _valid_judgment_record()
        record.pop("tool_profile", None)
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("tool_profile" in e for e in ctx.exception.errors))

    def test_missing_authority_mode_rejected(self):
        record = _valid_judgment_record()
        record.pop("authority_mode", None)
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("authority_mode" in e for e in ctx.exception.errors))

    def test_authority_mode_full_operator_rejected(self):
        # full_operator is deliberately NOT in authority_mode enum to prevent
        # tool-profile / canon-authority conflation.
        record = _valid_judgment_record(authority_mode="full_operator")
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("authority_mode" in e for e in ctx.exception.errors))

    def test_authority_mode_unknown_with_high_confidence_rejected(self):
        record = _valid_judgment_record(
            authority_mode="unknown",
            confidence="high",
            would_change_mind_if=(
                "If canon explicitly grants canon_write_authorized for this surface."
            ),
        )
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("authority_mode" in e and "unknown" in e for e in ctx.exception.errors))

    def test_authority_mode_unknown_with_low_confidence_allowed(self):
        record = _valid_judgment_record(authority_mode="unknown", confidence="low")
        result = self._emit(record)
        self.assertEqual(result["authority_mode"], "unknown")

    def test_authority_mode_canon_write_authorized_accepted(self):
        record = _valid_judgment_record(authority_mode="canon_write_authorized")
        result = self._emit(record)
        self.assertEqual(result["authority_mode"], "canon_write_authorized")

    def test_authority_mode_operator_authorized_exception_accepted(self):
        record = _valid_judgment_record(authority_mode="operator_authorized_exception")
        result = self._emit(record)
        self.assertEqual(result["authority_mode"], "operator_authorized_exception")

    def test_tool_profile_full_operator_string_does_not_imply_canon_authority(self):
        # tool_profile is a free string; 'full_operator' is allowed there, but
        # the validator does NOT cross-check it against authority_mode. This
        # records the discipline: tool access != canon authority.
        record = _valid_judgment_record(
            tool_profile="full_operator", authority_mode="limited_write"
        )
        result = self._emit(record)
        self.assertEqual(result["tool_profile"], "full_operator")
        self.assertEqual(result["authority_mode"], "limited_write")


# ---------------------------------------------------------------------------
# Calibration
# ---------------------------------------------------------------------------


class EmitDecisionCalibrationTests(_DecisionTestBase):
    def test_high_confidence_without_would_change_mind_if_rejected(self):
        record = _valid_judgment_record(confidence="high", would_change_mind_if="")
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        joined = " ".join(ctx.exception.errors).lower()
        self.assertIn("would_change_mind_if", joined)

    def test_missing_confidence_reason_rejected(self):
        record = _valid_judgment_record()
        record["confidence_reason"] = ""
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("confidence_reason" in e for e in ctx.exception.errors))

    def test_short_confidence_reason_rejected(self):
        record = _valid_judgment_record(confidence_reason="too short")
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(
            any("confidence_reason" in e and "short" in e for e in ctx.exception.errors)
        )

    def test_short_would_change_mind_if_rejected(self):
        record = _valid_judgment_record(would_change_mind_if="too short")
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(
            any("would_change_mind_if" in e and "short" in e for e in ctx.exception.errors)
        )

    def test_invalid_confidence_value_rejected(self):
        record = _valid_judgment_record(confidence="very high")
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("confidence" in e for e in ctx.exception.errors))


# ---------------------------------------------------------------------------
# Classification
# ---------------------------------------------------------------------------


class EmitDecisionClassificationTests(_DecisionTestBase):
    def test_final_tag_set_at_creation_rejected(self):
        record = _valid_judgment_record(final_tag="judgment_driven")
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("final_tag" in e for e in ctx.exception.errors))

    def test_nonempty_classification_history_at_creation_rejected(self):
        record = _valid_judgment_record(classification_history=[{"tag": "judgment_driven"}])
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("classification_history" in e for e in ctx.exception.errors))

    def test_canon_mandated_without_canon_refs_rejected(self):
        record = _valid_judgment_record(proposed_tag="canon_mandated", canon_refs=[])
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(
            any("canon_refs" in e and "canon_mandated" in e for e in ctx.exception.errors)
        )

    def test_canon_mandated_with_canon_refs_accepted(self):
        record = _valid_judgment_record(
            proposed_tag="canon_mandated",
            canon_refs=["CLAUDE.md PR Merge Policy"],
        )
        result = self._emit(record)
        self.assertEqual(result["proposed_tag"], "canon_mandated")

    def test_hybrid_without_canon_refs_rejected(self):
        # The conditional rule applies to both canon_mandated AND hybrid; this
        # test covers the hybrid branch that test_canon_mandated_without_canon_refs_rejected
        # leaves uncovered.
        record = _valid_judgment_record(proposed_tag="hybrid", canon_refs=[])
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("canon_refs" in e and "hybrid" in e for e in ctx.exception.errors))

    def test_judgment_driven_without_assumptions_or_uncertainties_rejected(self):
        record = _valid_judgment_record(
            proposed_tag="judgment_driven", assumptions=[], known_uncertainties=[]
        )
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("judgment_driven" in e for e in ctx.exception.errors))

    def test_invalid_proposed_tag_rejected(self):
        record = _valid_judgment_record(proposed_tag="bogus_tag")
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("proposed_tag" in e for e in ctx.exception.errors))


# ---------------------------------------------------------------------------
# Alternatives anti-gaming
# ---------------------------------------------------------------------------


class EmitDecisionAlternativesTests(_DecisionTestBase):
    def _alt(self, **overrides):
        base = {
            "option": "Treat as low-risk self-merge",
            "why_plausible": ("The implementation is standalone and does not wire into runtime."),
            "rejected_because": (
                "The task creates a new tool, which falls into operator-merge territory."
            ),
        }
        base.update(overrides)
        return base

    def test_alternative_rejected_trigger_with_empty_alternatives_rejected(self):
        record = _valid_judgment_record(trigger="alternative_rejected", alternatives_considered=[])
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("alternative_rejected" in e for e in ctx.exception.errors))

    def test_alternative_with_do_nothing_option_rejected(self):
        record = _valid_judgment_record(
            trigger="alternative_rejected",
            alternatives_considered=[self._alt(option="do nothing")],
        )
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("do nothing" in e for e in ctx.exception.errors))

    def test_alternative_with_ignore_the_task_option_rejected(self):
        record = _valid_judgment_record(
            trigger="alternative_rejected",
            alternatives_considered=[self._alt(option="ignore the task")],
        )
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("ignore the task" in e for e in ctx.exception.errors))

    def test_alternative_missing_why_plausible_rejected(self):
        record = _valid_judgment_record(
            trigger="alternative_rejected",
            alternatives_considered=[self._alt(why_plausible="")],
        )
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("why_plausible" in e for e in ctx.exception.errors))

    def test_alternative_short_rejected_because_rejected(self):
        record = _valid_judgment_record(
            trigger="alternative_rejected",
            alternatives_considered=[self._alt(rejected_because="too brief")],
        )
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("rejected_because" in e and "short" in e for e in ctx.exception.errors))

    def test_valid_alternative_accepted(self):
        record = _valid_judgment_record(
            trigger="alternative_rejected",
            alternatives_considered=[self._alt()],
        )
        result = self._emit(record)
        self.assertEqual(len(result["alternatives_considered"]), 1)


# ---------------------------------------------------------------------------
# Grading invariants at creation time
# ---------------------------------------------------------------------------


class EmitDecisionGradingTests(_DecisionTestBase):
    def test_actual_outcome_set_at_creation_rejected(self):
        record = _valid_judgment_record(actual_outcome="some outcome")
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("actual_outcome" in e for e in ctx.exception.errors))

    def test_grading_state_graded_correct_at_creation_rejected(self):
        record = _valid_judgment_record(grading_state="graded_correct")
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("grading_state" in e for e in ctx.exception.errors))

    def test_outcome_status_set_at_creation_rejected(self):
        record = _valid_judgment_record(outcome_status="success")
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("outcome_status" in e for e in ctx.exception.errors))

    def test_invalid_grading_state_rejected(self):
        record = _valid_judgment_record(grading_state="bogus_state")
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("grading_state" in e for e in ctx.exception.errors))


# ---------------------------------------------------------------------------
# Evidence + decision summary
# ---------------------------------------------------------------------------


class EmitDecisionEvidenceTests(_DecisionTestBase):
    def test_missing_expected_outcome_rejected(self):
        record = _valid_judgment_record()
        record["expected_outcome"] = ""
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("expected_outcome" in e for e in ctx.exception.errors))

    def test_invalid_trigger_rejected(self):
        record = _valid_judgment_record(trigger="bogus_trigger")
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(any("trigger" in e for e in ctx.exception.errors))

    def test_empty_decision_narrative_rejected(self):
        record = _valid_judgment_record(decision="")
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        joined = " ".join(ctx.exception.errors).lower()
        self.assertIn("decision", joined)

    def test_short_decision_narrative_rejected(self):
        record = _valid_judgment_record(decision="x")
        with self.assertRaises(EmitDecisionError) as ctx:
            self._emit(record)
        self.assertTrue(
            any("decision" in e.lower() and "short" in e.lower() for e in ctx.exception.errors)
        )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


EMIT_DECISION_PATH = REPO_ROOT / "tools" / "emit_decision.py"


class EmitDecisionCLITests(unittest.TestCase):
    """Exercise the CLI as a real subprocess. Uses MIRU_DECISIONS_LOG_PATH for hermetic writes."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.tmp_dir = Path(self._tmp.name)
        self.cli_log = self.tmp_dir / "decisions.jsonl"

    def _run(self, *, record=None, raw=None, use_stdin=False):
        env = {
            **os.environ,
            "MIRU_DECISIONS_LOG_PATH": str(self.cli_log),
        }
        payload = json.dumps(record) if record is not None else (raw or "")

        if use_stdin:
            return subprocess.run(
                [sys.executable, str(EMIT_DECISION_PATH)],
                input=payload,
                text=True,
                capture_output=True,
                env=env,
                cwd=str(REPO_ROOT),
            )
        else:
            input_file = self.tmp_dir / "input.json"
            input_file.write_text(payload, encoding="utf-8")
            return subprocess.run(
                [sys.executable, str(EMIT_DECISION_PATH), "--input", str(input_file)],
                text=True,
                capture_output=True,
                env=env,
                cwd=str(REPO_ROOT),
            )

    def test_input_flag_works(self):
        result = self._run(record=_valid_judgment_record(), use_stdin=False)
        self.assertEqual(result.returncode, 0, msg=f"stderr={result.stderr}")
        self.assertIn("[emit_decision] written to", result.stderr)
        # decision_id printed on stdout (uuid4().hex = 32 chars)
        self.assertEqual(len(result.stdout.strip()), 32)
        self.assertTrue(self.cli_log.exists())
        lines = self.cli_log.read_text(encoding="utf-8").splitlines()
        self.assertEqual(len(lines), 1)

    def test_stdin_works(self):
        result = self._run(record=_valid_judgment_record(), use_stdin=True)
        self.assertEqual(result.returncode, 0, msg=f"stderr={result.stderr}")
        self.assertEqual(len(result.stdout.strip()), 32)

    def test_json_parse_failure_returns_clear_error(self):
        result = self._run(raw="this is not json", use_stdin=True)
        self.assertEqual(result.returncode, 2)
        self.assertIn("[decision-validation]", result.stderr)
        self.assertIn("invalid JSON", result.stderr)

    def test_validation_error_human_readable(self):
        record = _valid_judgment_record(confidence="high", would_change_mind_if="")
        result = self._run(record=record, use_stdin=True)
        self.assertEqual(result.returncode, 1)
        lines = [ln for ln in result.stderr.splitlines() if ln.startswith("[decision-validation]")]
        self.assertGreater(len(lines), 0)

    def test_empty_stdin_returns_clear_error(self):
        result = self._run(raw="", use_stdin=True)
        self.assertEqual(result.returncode, 2)
        self.assertIn("[decision-validation]", result.stderr)


if __name__ == "__main__":
    unittest.main()
