"""Miru local helper lane — Ollama + Gemma 4 advisory assistance.

All outputs from this module are **advisory only**.  They must never:
- override evidence reconciliation or contradiction flags
- bypass is_correction_coarse()
- write directly to canonical DBs (card_catalog, image_assets, etc.)
- auto-promote candidates
- weaken any governed gate

The helper lane is disabled by default and must be explicitly enabled
via the MIRU_HELPER_ENABLED=1 environment variable.
"""

from __future__ import annotations

import json
import logging
import os
import threading
import urllib.error
import urllib.request
from typing import Any

log = logging.getLogger(__name__)

# ── Configuration ────────────────────────────────────────────────────────

HELPER_ENABLED = os.getenv("MIRU_HELPER_ENABLED", "").strip().lower() in ("1", "true", "yes")
HELPER_MODEL = os.getenv("MIRU_HELPER_MODEL", "gemma4:e4b")
HELPER_BASE_URL = os.getenv("MIRU_HELPER_BASE_URL", "http://127.0.0.1:11434/v1")
HELPER_TIMEOUT = float(os.getenv("MIRU_HELPER_TIMEOUT_SECONDS", "90"))

# Session override (None = follow HELPER_ENABLED from environment).
_HELPER_RUNTIME_OVERRIDE: bool | None = None
_HELPER_LOCK = threading.Lock()

# Advisory watermark appended to all helper outputs.
_ADVISORY_TAG = "[Generated by Miru local helper — advisory only, not authoritative]"


def effective_helper_enabled() -> bool:
    """Whether the helper lane is on for this process (env or runtime toggle)."""
    with _HELPER_LOCK:
        if _HELPER_RUNTIME_OVERRIDE is not None:
            return bool(_HELPER_RUNTIME_OVERRIDE)
    return HELPER_ENABLED


def set_helper_runtime_override(value: bool | None) -> None:
    """Set or clear session-only helper lane toggle. None = follow MIRU_HELPER_ENABLED."""
    global _HELPER_RUNTIME_OVERRIDE
    with _HELPER_LOCK:
        _HELPER_RUNTIME_OVERRIDE = value


def _probe_ollama_tags() -> bool:
    try:
        req = urllib.request.Request(
            HELPER_BASE_URL.rstrip("/").rsplit("/v1", 1)[0] + "/api/tags",
            method="GET",
        )
        with urllib.request.urlopen(req, timeout=5) as resp:
            return resp.status == 200
    except Exception:
        return False


def is_helper_available() -> bool:
    """Return True if the helper lane is enabled and the endpoint is reachable."""
    if not effective_helper_enabled():
        return False
    return _probe_ollama_tags()


def helper_status() -> dict[str, Any]:
    """Return a status dict for the helper lane (safe for API exposure)."""
    lane = effective_helper_enabled()
    reachable = False
    if lane:
        reachable = _probe_ollama_tags()
    with _HELPER_LOCK:
        override_active = _HELPER_RUNTIME_OVERRIDE is not None
    return {
        "enabled": lane,
        "envEnabled": HELPER_ENABLED,
        "runtimeOverride": override_active,
        "model": HELPER_MODEL,
        "base_url": HELPER_BASE_URL,
        "reachable": reachable,
    }


# ── Low-level chat completion ────────────────────────────────────────────

def _chat_complete(
    messages: list[dict[str, str]],
    *,
    max_tokens: int = 2048,
    temperature: float = 0.3,
) -> str | None:
    """Call the Ollama OpenAI-compatible chat completions endpoint.

    Returns the assistant message content, or None on failure.
    """
    if not effective_helper_enabled():
        return None

    url = HELPER_BASE_URL.rstrip("/") + "/chat/completions"
    body = {
        "model": HELPER_MODEL,
        "messages": messages,
        "max_tokens": max_tokens,
        "temperature": temperature,
    }

    try:
        req = urllib.request.Request(
            url,
            data=json.dumps(body).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=HELPER_TIMEOUT) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            choices = data.get("choices") or []
            if choices:
                return (choices[0].get("message") or {}).get("content")
    except (urllib.error.URLError, urllib.error.HTTPError, json.JSONDecodeError) as exc:
        log.warning("helper chat completion failed: %s", exc)
    except Exception as exc:
        log.warning("helper unexpected error: %s", exc)
    return None


# ── Safe helper functions (advisory only) ────────────────────────────────

_SYSTEM_PREAMBLE = (
    "You are a helper assistant for Miru, a TCG card data governance system. "
    "Your outputs are advisory only — they do not have authority over evidence, "
    "contradictions, or candidate promotion. Be concise and factual. "
    "Do not invent card data, prices, or image metadata."
)


def summarize_candidate_rationale(candidate: dict[str, Any]) -> dict[str, Any]:
    """Generate an advisory summary of why a candidate was prepared.

    Returns {"ok": bool, "summary": str, "advisory": True}.
    """
    correction = candidate.get("proposed_correction") or "{}"
    if isinstance(correction, str):
        try:
            correction = json.loads(correction)
        except (json.JSONDecodeError, TypeError):
            pass

    prompt = (
        f"A correction candidate has been prepared for card {candidate.get('card_code', '?')} "
        f"(variant: {candidate.get('variant_key', '?')}).\n"
        f"Issue type: {candidate.get('issue_type', '?')}\n"
        f"Proposed correction: {json.dumps(correction, indent=1)}\n"
        f"Approval rate: {candidate.get('approval_rate', 0):.0%} "
        f"({candidate.get('approve_count', 0)}/{candidate.get('decision_count', 0)} reviews)\n"
        f"Eligibility path: {candidate.get('eligibility_path', '?')}\n\n"
        "Write a 2-3 sentence summary explaining why this candidate was prepared "
        "and what the proposed correction would change. Be factual and concise."
    )

    result = _chat_complete([
        {"role": "system", "content": _SYSTEM_PREAMBLE},
        {"role": "user", "content": prompt},
    ], max_tokens=2048)

    if result:
        return {"ok": True, "summary": result.strip() + "\n\n" + _ADVISORY_TAG, "advisory": True}
    return {"ok": False, "summary": "Helper unavailable.", "advisory": True}


def explain_elevation(candidate: dict[str, Any]) -> dict[str, Any]:
    """Generate an advisory explanation of why a candidate requires elevated review.

    Returns {"ok": bool, "explanation": str, "advisory": True}.
    """
    prompt = (
        f"A correction candidate for card {candidate.get('card_code', '?')} "
        f"has been escalated to ELEVATED_REVIEW_REQUIRED.\n"
        f"Elevation reason: {candidate.get('elevation_reason', 'not specified')}\n"
        f"Contradiction flag: {'active' if candidate.get('contradiction_flag') else 'inactive'}\n"
        f"Issue type: {candidate.get('issue_type', '?')}\n"
        f"Proposed correction: {candidate.get('proposed_correction', '{}')}\n\n"
        "Explain in 2-3 sentences why this candidate requires elevated review. "
        "What does the contradiction or elevation reason mean for an operator reviewing this?"
    )

    result = _chat_complete([
        {"role": "system", "content": _SYSTEM_PREAMBLE},
        {"role": "user", "content": prompt},
    ], max_tokens=2048)

    if result:
        return {"ok": True, "explanation": result.strip() + "\n\n" + _ADVISORY_TAG, "advisory": True}
    return {"ok": False, "explanation": "Helper unavailable.", "advisory": True}


def draft_review_note(
    issue_type: str,
    because: str,
    card_code: str = "",
    variant_key: str = "",
) -> dict[str, Any]:
    """Draft a cleaned-up operator review note from raw input.

    Returns {"ok": bool, "draft": str, "advisory": True}.
    """
    prompt = (
        f"An operator is reviewing card {card_code or '?'} "
        f"(variant: {variant_key or '?'}) "
        f"and flagged issue: {issue_type}.\n"
        f"Their raw note: \"{because}\"\n\n"
        "Rewrite this as a clear, concise operator note (1-2 sentences). "
        "Keep the original meaning. Do not add facts not in the original."
    )

    result = _chat_complete([
        {"role": "system", "content": _SYSTEM_PREAMBLE},
        {"role": "user", "content": prompt},
    ], max_tokens=1024)

    if result:
        return {"ok": True, "draft": result.strip() + "\n\n" + _ADVISORY_TAG, "advisory": True}
    return {"ok": False, "draft": "Helper unavailable.", "advisory": True}


def suggest_correction_detail(
    issue_type: str,
    card_code: str,
    variant_key: str = "",
    because: str = "",
) -> dict[str, Any]:
    """Suggest structured correction detail fields for an issue.

    Returns {"ok": bool, "suggestion": dict, "advisory": True}.
    The suggestion is never auto-applied — the operator must confirm.
    """
    prompt = (
        f"A TCG card review flagged issue '{issue_type}' for card {card_code} "
        f"(variant: {variant_key or 'default'}).\n"
        f"Operator note: \"{because}\"\n\n"
        "Based on the issue type, suggest which database table and column "
        "are most likely affected. Return ONLY a JSON object with these fields "
        "(omit fields you cannot determine):\n"
        '{"target_table": "...", "target_column": "...", "notes": "..."}\n\n'
        "Known tables: card_catalog, card_variants, image_assets, printing_market_map.\n"
        "Return only the JSON object, no other text."
    )

    result = _chat_complete([
        {"role": "system", "content": _SYSTEM_PREAMBLE},
        {"role": "user", "content": prompt},
    ], max_tokens=1024, temperature=0.1)

    if result:
        cleaned = result.strip()
        # Try to extract JSON from the response.
        try:
            # Handle markdown code fences if present.
            if "```" in cleaned:
                start = cleaned.index("{")
                end = cleaned.rindex("}") + 1
                cleaned = cleaned[start:end]
            suggestion = json.loads(cleaned)
            if isinstance(suggestion, dict):
                return {"ok": True, "suggestion": suggestion, "advisory": True}
        except (json.JSONDecodeError, ValueError):
            pass
        return {"ok": True, "suggestion": {"notes": cleaned}, "advisory": True}
    return {"ok": False, "suggestion": {}, "advisory": True}
