"""PRO-156 — one-shot Step Zero JSONL import into miru_memory.db.

Imports rows from data/routing_history.jsonl and data/cc_completion_log.jsonl
into the routing_decisions table with outcome='legacy'. Preserves the original
JSON row in the meta column. Idempotent if the DB is empty; safe to re-run
because rows have UUID PKs auto-generated by the schema default.

This script is one-shot: it runs once at memory-layer build time. Per PRO-156
scope, JSONL writers (n8n workflows, helper scripts) are left untouched in
this ticket — that's a follow-up after memory DB is proven.

Run from repo root:
    python tools/miru_memory_import.py

Halts and reports if a row fails to import, surfaces malformed rows per
PRO-156 escalation rule.
"""

from __future__ import annotations

import argparse
import json
import sqlite3
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
DB_PATH = REPO_ROOT / "data" / "miru_memory.db"
ROUTING_HISTORY = REPO_ROOT / "data" / "routing_history.jsonl"
CC_LOG = REPO_ROOT / "data" / "cc_completion_log.jsonl"

# PRO-156 schema — applied to a fresh DB by --bootstrap. Mirror of the spec
# locked in the Linear ticket; do not edit without operator approval.
SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS routing_decisions (
  id          TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  created_at  TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  task_slug   TEXT NOT NULL,
  worker      TEXT NOT NULL,
  outcome     TEXT CHECK(outcome IN ('success','failure','partial','deferred','legacy')),
  notes       TEXT,
  thread_ref  TEXT,
  meta        TEXT
);

CREATE TABLE IF NOT EXISTS agenda (
  id          TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  created_at  TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at  TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  title       TEXT NOT NULL,
  status      TEXT CHECK(status IN ('active','deferred','done','blocked')) DEFAULT 'active',
  deadline    TEXT,
  reeval_at   TEXT,
  priority    INTEGER DEFAULT 3,
  context     TEXT,
  linear_id   TEXT,
  meta        TEXT
);

CREATE TABLE IF NOT EXISTS decisions (
  id          TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  created_at  TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  domain      TEXT,
  decision    TEXT NOT NULL,
  supersedes  TEXT REFERENCES decisions(id),
  source      TEXT,
  meta        TEXT
);

CREATE TABLE IF NOT EXISTS worker_perf (
  id          TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  created_at  TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  worker      TEXT NOT NULL,
  task_type   TEXT,
  outcome     TEXT,
  notes       TEXT,
  meta        TEXT
);

CREATE TABLE IF NOT EXISTS stack_state (
  key         TEXT PRIMARY KEY,
  value       TEXT,
  updated_at  TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS peer_review (
  id          TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  created_at  TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  source      TEXT NOT NULL,
  topic       TEXT NOT NULL,
  summary     TEXT NOT NULL,
  verdict     TEXT CHECK(verdict IN ('adopted','rejected','deferred','pending')) DEFAULT 'pending',
  adopted_in  TEXT REFERENCES decisions(id),
  thread_ref  TEXT
);
"""


def _bootstrap_db(db_path: Path) -> None:
    """Create DB file with schema + WAL mode if it doesn't already exist."""
    db_path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(db_path))
    try:
        conn.executescript(SCHEMA_SQL)
        conn.execute("PRAGMA journal_mode=WAL;")
        conn.commit()
    finally:
        conn.close()


def _row_from_routing_history(r: dict[str, Any]) -> dict[str, Any]:
    task_slug = (
        r.get("task_identifier") or r.get("issue_identifier") or r.get("task_id") or "unknown"
    )
    worker = r.get("chosen_worker") or r.get("worker") or "unknown"
    notes = f"original_outcome={r.get('outcome', '<missing>')}"
    return {
        "created_at": r.get("timestamp"),
        "task_slug": task_slug,
        "worker": worker,
        "outcome": "legacy",
        "notes": notes,
        "thread_ref": r.get("trace_id"),
        "meta": json.dumps(r, separators=(",", ":")),
    }


def _row_from_cc_log(r: dict[str, Any]) -> dict[str, Any]:
    notes_parts = []
    if r.get("phase"):
        notes_parts.append(f"phase={r['phase']}")
    if r.get("status"):
        notes_parts.append(f"status={r['status']}")
    return {
        "created_at": r.get("timestamp"),
        "task_slug": r.get("ticket_id") or "unknown",
        "worker": "claude-code",
        "outcome": "legacy",
        "notes": "; ".join(notes_parts) or None,
        "thread_ref": r.get("branch") or (str(r["pr_number"]) if r.get("pr_number") else None),
        "meta": json.dumps(r, separators=(",", ":")),
    }


def _parse_jsonl(path: Path) -> tuple[list[dict[str, Any]], list[tuple[int, str]]]:
    rows: list[dict[str, Any]] = []
    bad: list[tuple[int, str]] = []
    with path.open(encoding="utf-8") as f:
        for lineno, raw in enumerate(f, start=1):
            line = raw.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError as e:
                bad.append((lineno, f"{e}: {line[:200]}"))
    return rows, bad


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--db",
        default=str(DB_PATH),
        help="Path to miru_memory.db (default: data/miru_memory.db at repo root)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Parse and prepare rows but do not write to DB. Reports counts only.",
    )
    parser.add_argument(
        "--bootstrap",
        action="store_true",
        help="Create the DB with schema + WAL mode if it doesn't exist before importing.",
    )
    args = parser.parse_args(argv)

    db_path = Path(args.db).resolve()
    print(f"DB: {db_path}")
    print(f"Routing history: {ROUTING_HISTORY}")
    print(f"CC log:          {CC_LOG}")
    print()

    # Bugbot fix #1 (MED, PR #31): apply --bootstrap unconditionally when the
    # flag is set, not only when the DB file is missing. SCHEMA_SQL uses
    # `CREATE TABLE IF NOT EXISTS` so re-applying is idempotent and ensures
    # schema correctness against a partial/manually-created DB file.
    if args.bootstrap:
        action = "bootstrapping" if not db_path.exists() else "re-applying schema (idempotent)"
        print(f"--bootstrap: {action} at {db_path} ...")
        _bootstrap_db(db_path)
        print("schema applied, WAL mode enabled")
    elif not db_path.exists():
        print(
            f"ERROR: DB does not exist at {db_path}. Re-run with --bootstrap to create it.",
            file=sys.stderr,
        )
        return 2

    rh_rows, rh_bad = _parse_jsonl(ROUTING_HISTORY)
    cc_rows, cc_bad = _parse_jsonl(CC_LOG)

    print(f"routing_history.jsonl rows: {len(rh_rows)} (bad: {len(rh_bad)})")
    print(f"cc_completion_log.jsonl rows: {len(cc_rows)} (bad: {len(cc_bad)})")

    if rh_bad or cc_bad:
        print("\nMALFORMED ROWS — halting per PRO-156 escalation rule:", file=sys.stderr)
        for lineno, msg in rh_bad[:5]:
            print(f"  routing_history.jsonl:{lineno}: {msg}", file=sys.stderr)
        for lineno, msg in cc_bad[:5]:
            print(f"  cc_completion_log.jsonl:{lineno}: {msg}", file=sys.stderr)
        return 3

    prepared = [_row_from_routing_history(r) for r in rh_rows] + [
        _row_from_cc_log(r) for r in cc_rows
    ]
    expected = len(rh_rows) + len(cc_rows)
    print(f"prepared rows for insert: {len(prepared)} (expected {expected})")
    assert len(prepared) == expected

    if args.dry_run:
        # Bugbot fix #2 (LOW, PR #31): guard prepared[0] when both inputs are
        # empty (zero valid rows on either side) to avoid IndexError.
        print("\n[--dry-run] not writing to DB.")
        if prepared:
            print("Sample row:")
            print(json.dumps(prepared[0], indent=2)[:500])
        else:
            print("No rows to insert (both source files empty).")
        return 0

    conn = sqlite3.connect(str(db_path))
    try:
        # Confirm WAL still active (defensive — should already be set at create time)
        mode = conn.execute("PRAGMA journal_mode;").fetchone()[0]
        print(f"DB journal_mode: {mode}")

        before = conn.execute("SELECT COUNT(*) FROM routing_decisions;").fetchone()[0]
        print(f"routing_decisions rows BEFORE import: {before}")

        with conn:
            conn.executemany(
                """
                INSERT INTO routing_decisions
                  (created_at, task_slug, worker, outcome, notes, thread_ref, meta)
                VALUES
                  (:created_at, :task_slug, :worker, :outcome, :notes, :thread_ref, :meta)
                """,
                prepared,
            )

        after = conn.execute("SELECT COUNT(*) FROM routing_decisions;").fetchone()[0]
        print(f"routing_decisions rows AFTER import: {after}")
        delta = after - before
        if delta != expected:
            print(
                f"ERROR: row delta mismatch. Inserted {delta}, expected {expected}.",
                file=sys.stderr,
            )
            return 4
        print(f"\nIMPORT OK — inserted {delta} rows (expected {expected})")
    finally:
        conn.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
