-- Migration m002: Leader Hub intelligence tables
-- Target database : miru_deck_intel.db  (must already exist)
-- Applied by      : tools/miru_migrate_db.py --target deck_intel
--
-- All statements are idempotent (CREATE ... IF NOT EXISTS).
-- Run this migration at any time after miru_deck_intel.db exists.
-- miru_deck_intel.db is created by miru_import_decklist.py on first run.
--
-- See docs/miru_db_schema.md §4 for full field reference and design rationale.

-- ────────────────────────────────────────────────────────────────────────────
-- TABLE: leader_profiles
-- ────────────────────────────────────────────────────────────────────────────
-- Summary-level metadata per leader, computed from the existing signal tables.
-- This is a pipeline cache/aggregate — the pipeline recomputes it from
-- leader_card_signals, archetype_profiles, and decklists.
--
-- Written by: pipeline tools (miru_bundle_leader_insight.py or equivalent)
-- Read by:    dashboard leader page, AI server

CREATE TABLE IF NOT EXISTS leader_profiles (
    leader_code             TEXT    PRIMARY KEY,
    -- Soft reference to cards.canonical_code (type=Leader) in card_catalog.db.
    -- Not a SQL foreign key — the catalog lives in a separate file.

    decks_sampled           INTEGER NOT NULL DEFAULT 0,
    -- COUNT(DISTINCT deck_uid) from decklists WHERE leader_code = this.
    -- Recomputed by the pipeline on each refresh.

    confidence_label        TEXT    NOT NULL DEFAULT 'low',
    -- Derived from decks_sampled. Thresholds match miru_archetype_preview.py:
    --   'low'    : decks_sampled < 5
    --   'medium' : 5 <= decks_sampled <= 14
    --   'strong' : decks_sampled >= 15

    archetype_count         INTEGER NOT NULL DEFAULT 0,
    -- COUNT(DISTINCT archetype_id) from archetype_profiles WHERE leader_code = this.

    dominant_archetype_id   TEXT    NOT NULL DEFAULT '',
    -- archetype_id with the highest deck_count or coverage for this leader.
    -- Empty string if no archetypes have been computed yet.

    identity_tags_json      TEXT    NOT NULL DEFAULT '[]',
    -- JSON array of string tags derived from trait signals and cost curve shape.
    -- Example: ["aggro", "straw-hat", "rush", "red"]

    playstyle_summary       TEXT    NOT NULL DEFAULT '',
    -- Short Miru-generated prose summary (1–3 sentences).
    -- Written by miru_bundle_leader_insight.py or a future synthesis step.

    updated_at              INTEGER NOT NULL
    -- Unix timestamp of last pipeline recompute.
);

-- ────────────────────────────────────────────────────────────────────────────
-- TABLE: leader_budget_builds
-- ────────────────────────────────────────────────────────────────────────────
-- Structured budget build entries generated by the intelligence pipeline.
-- Not user-created content — these are written by pipeline tools using data
-- from leader_card_signals to identify cost-efficient card selections.
--
-- One row per (leader_code, format_code, budget_tier) — enforced by UNIQUE.
-- Upsert with INSERT OR REPLACE when the pipeline refreshes.

CREATE TABLE IF NOT EXISTS leader_budget_builds (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    leader_code     TEXT    NOT NULL,
    -- Soft reference to leader_profiles.leader_code (and ultimately cards.canonical_code).

    format_code     TEXT    NOT NULL DEFAULT '',
    -- Matches decklists.format_code. Empty string = format-agnostic.
    -- Allowed values: '', 'standard', 'block', 'unlimited'

    budget_tier     TEXT    NOT NULL DEFAULT 'budget',
    -- Allowed values: 'budget', 'mid', 'premium'
    -- One row per (leader_code, format_code, budget_tier).

    name            TEXT    NOT NULL,
    -- Display name shown on the leader page.
    -- Example: "Budget Luffy Aggro", "Mid-Range Red Luffy"

    description     TEXT    NOT NULL DEFAULT '',
    -- 1–3 sentence rationale for this build tier.

    est_cost_usd    REAL,
    -- Estimated market value in USD. NULL if unknown or not computed.

    core_cards_json TEXT    NOT NULL DEFAULT '[]',
    -- JSON array of core card entries. Schema:
    -- [{"card_code": "OP01-001", "quantity": 4, "role": "core"}, ...]

    flex_cards_json TEXT    NOT NULL DEFAULT '[]',
    -- JSON array of flex card entries. Schema:
    -- [{"card_code": "OP01-060", "quantity": 2, "role": "flex",
    --   "budget_alt": "OP02-011"}, ...]
    -- flex entries may include a "budget_alt" card_code as a cheaper substitute.

    created_at      INTEGER NOT NULL,
    updated_at      INTEGER NOT NULL,
    -- Both: Unix timestamps (int(time.time()) in Python).

    UNIQUE(leader_code, format_code, budget_tier)
    -- Use INSERT OR REPLACE to upsert on pipeline refresh.
);

-- ────────────────────────────────────────────────────────────────────────────
-- INDEXES
-- ────────────────────────────────────────────────────────────────────────────

-- leader_profiles.leader_code is PRIMARY KEY — no additional index needed
-- for exact leader lookups.

-- List all leaders by confidence tier (e.g. "show only well-sampled leaders")
CREATE INDEX IF NOT EXISTS idx_leader_profiles_confidence
    ON leader_profiles(confidence_label);

-- List budget builds for a leader + format (most common leader page query)
CREATE INDEX IF NOT EXISTS idx_leader_budget_leader
    ON leader_budget_builds(leader_code, format_code);
